# Generated by Django 4.2.3 on 2023-07-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
